from typing import Any, List, Optional
from uuid import UUID

from fastapi import APIRouter, Depends
from sqlalchemy import and_
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.future import select

from app.api.deps import get_current_user, get_db
from app.models.forecast import Forecast
from app.schemas.forecast import ForecastResponse

router = APIRouter()


@router.get("/", response_model=List[ForecastResponse])
async def read_forecasts(
    db: AsyncSession = Depends(get_db),
    current_user: Any = Depends(get_current_user),
    product_id: Optional[UUID] = None,
) -> Any:
    """Retrieve 30-day forecast generated by the machine learning model."""
    query = select(Forecast).order_by(Forecast.forecast_date.asc())
    
    if product_id:
        query = query.where(Forecast.product_id == product_id)
        
    result = await db.execute(query)
    forecasts = result.scalars().all()
    return forecasts
